name: build

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10" ]

    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
        if [ -f ./engforge/datastores/datastores_requirements.txt ]; then pip install -r ./engforge/datastores/datastores_requirements.txt; fi    

    - name: Display Python Version
      run: python -c "import sys; print(sys.version)"

    - name: Run tests
      run: python -m unittest discover ./test/

    - uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "./engforge"