name: "Pull Request Docs Check"
on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.md'
      - '**.rst'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -e .     
        pip install -r ./docs/requirements.txt

    - name: make html
      run: |
        cd docs
        make html
        
    - uses: actions/upload-artifact@v4
      with:
        name: DocumentationHTML
        path: docs/_build/html/


    
    # - uses: ammaraskar/sphinx-action@master
    #   with:
    #     docs-folder: "docs/"
        
        # - uses: actions/checkout@v2
    # - name: Format code with black
    #   run: |
    #     pip install black
    #     black -l 80 --include="\.py" .
    #     
    # - name: Commit changes
    #   uses: EndBug/add-and-commit@v4
    #   with:
    #     author_name: ${{ github.actor }}
    #     author_email: ${{ github.actor }}@users.noreply.github.com
    #     message: "Built Documentation / Format code with black"
    #     add: "."       

    # Create an artifact out of the previously built pdf.
    # - uses: actions/upload-artifact@v1
    #   with:
    #     name: Documentation
    #     path: docs2/build/latex/documentation.pdf
