name: "Pull Request Docs Check"
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/build/html/

    # - uses: actions/checkout@v2
    # - name: Format code with black
    #   run: |
    #     pip install black
    #     black -l 80 --include="\.py" .
    #     
    # - name: Commit changes
    #   uses: EndBug/add-and-commit@v4
    #   with:
    #     author_name: ${{ github.actor }}
    #     author_email: ${{ github.actor }}@users.noreply.github.com
    #     message: "Built Documentation / Format code with black"
    #     add: "."       

    # Create an artifact out of the previously built pdf.
    # - uses: actions/upload-artifact@v1
    #   with:
    #     name: Documentation
    #     path: docs2/build/latex/documentation.pdf