name: "docs"
on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.md'
      - '**.rst'
      - '**.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        if [ -f "./engforge/datastores/datastores_requirements.txt" ]; then pip install -r ./engforge/datastores/datastores_requirements.txt; fi
        pip install -r ./docs/requirements.txt

    - name: make html
      run: |
        cd docs
        make html
        
    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: DocumentationHTML
    #     path: docs/_build/html/

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: 'docs/_build/html/'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4