name: "docs"
on:
  pull_request:
    paths:
      - '**.py'
      - '**.md'
      - '**.rst'
      - 'docs/**'

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -e .[all]
        pip install -r ./docs/requirements.txt

    - name: Test documentation build
      run: |
        cd docs
        make html

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation-preview
        path: docs/_build/html/